export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PORTFOLIO: '/portfolio',
  TRANSACTION_HISTORY: '/transactions',
  STOCK_DETAILS: '/stocks/:symbol',
  WATCHLIST: '/watchlist',
  ALERTS: '/alerts',
  TAX_REPORTS: '/tax-reports',
  SCREENER: '/screener',
  US_SCREENER: '/us-screener',
  SETTINGS: '/settings',
} as const;
